version: '3.12'

services:

  web:
    build: .
    command: python manage.py runserver 0:8000
    volumes:
      - .:/backend
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=db
    ports:
      - 8000:8000
    container_name: backend
    networks:
      - climatewavers
    depends_on:
      - db

  db:
    image: mysql
    env_file:
      - ./.env
    ports:
      - 3306:3306
    container_name: backend.db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - climatewavers
  
volumes:
  mysql_data:
    name: "disaXta-data"
    external: true

networks:
  climatewavers:
    driver: bridge
    external: true
    name: climatewavers
