version: '3.12'

services:

  web:
    build: .
    command: npm start
    image: oauth
    volumes:
      - .:/oauth
      - node_modules:/oauth/node_modules
      - .env:/oauth/.env
    env_file:
      - ./.env
    ports:
      - 3000:3000
    container_name: oauth
    networks:
      - climatewavers
    depends_on:
      - db

  db:
    image: mysql
    env_file:
      - ./.env
    ports:
      - 3306:3306
    container_name: oauth.db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - climatewavers
  
volumes:
  mysql_data:
    name: "oauth-data"
    external: true
  node_modules:
  .env:

networks:
  climatewavers:
    driver: bridge
    external: true
    name: climatewavers
