# Generated by Django 5.0 on 2024-03-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='following',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelTable(
            name='follower',
            table=None,
        ),
        migrations.AlterModelTable(
            name='following',
            table=None,
        ),
    ]
