# Generated by Django 5.0 on 2024-03-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_comment_content_comment_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='user',
        ),
    ]
