# Generated by Django 5.0 on 2024-03-24 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_customtoken_token_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('community', 'Community'), ('education', 'Education')], default='community', max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
