# Generated by Django 5.0 on 2024-03-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_post_category_alter_token_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='subcomments',
            new_name='comments',
        ),
    ]
